-- MySQL Script generated by MySQL Workbench
-- mar 09 feb 2021 22:24:28 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Merced_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Merced_DB
-- -----------------------------------------------------
-- CREATE DATABASE IF NOT EXISTS `Merced_DB` ;
-- USE `Merced_DB` ;

-- -----------------------------------------------------
-- Table `Merced_DB`.`organization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merced_DB`.`organization` (
  `id_organization` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_name` VARCHAR(50) NOT NULL,
  `intervention_area` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `blacklist` TEXT(2) NOT NULL,
  PRIMARY KEY (`id_organization`),
  UNIQUE INDEX `id_organizacion_UNIQUE` (`id_organization` ASC));

-- -----------------------------------------------------
-- Table `Merced_DB`.`program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`program` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`program` (
  `id_program` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `program_code` VARCHAR(45) NOT NULL,
  `program_name` VARCHAR(45) NOT NULL,
  `id_organization` INT UNSIGNED NOT NULL,
  `coordination` VARCHAR(45) NOT NULL,
  `in_account` VARCHAR(30) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `end_date` VARCHAR(30),
  UNIQUE INDEX `id_programa_UNIQUE` (`id_program` ASC),
  PRIMARY KEY (`id_program`, `id_organization`),
  INDEX `fk_program_organization1_idx` (`id_organization` ASC),
  CONSTRAINT `fk_program_orgnization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `Merced_DB`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merced_DB`.`contact` (
  `id_contact` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(10) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_organization` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_contact`),
  INDEX `fk_contact_organization1_idx` (`id_organization` ASC),
  CONSTRAINT `fk_contact_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `Merced_DB`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merced_DB`.`employee` (
  `id_employee` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`),
  UNIQUE INDEX `id_leader_UNIQUE` (`id_employee` ASC));

-- -----------------------------------------------------
-- Table `Merced_DB`.`program_leader`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merced_DB`.`program_leader` (
  `id_program` INT UNSIGNED NOT NULL,
  `id_employee` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_program`, `id_employee`),
  INDEX `fk_program_has_employee_employee1_idx` (`id_employee` ASC),
  INDEX `fk_program_has_employee_program_idx` (`id_program` ASC),
  CONSTRAINT `fk_program_has_employee_program`
    FOREIGN KEY (`id_program`)
    REFERENCES `Merced_DB`.`program` (`id_program`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_has_employee_employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Merced_DB`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `Merced_DB`.`program_organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`program_organization` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`program_organization` (
  `id_part` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_organization` INT UNSIGNED NOT NULL,
  `id_program` INT UNSIGNED NOT NULL,
  `year` YEAR(4) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  `resources` VARCHAR(20) NOT NULL,
  `consultor` VARCHAR(45) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `comments` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_part`,`id_organization`, `id_program`),
  INDEX `fk_program_has_organization_organization1_idx` (`id_organization` ASC),
  INDEX `fk_program_organization_program1_idx` (`id_program` ASC),
  CONSTRAINT `fk_program_has_organization_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_organization_program1`
    FOREIGN KEY (`id_program`)
    REFERENCES `Merced_DB`.`program` (`id_program`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `Merced_DB`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merced_DB`.`user` (
  `password` VARCHAR(45) NOT NULL,
  `id_employee` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`password`, `id_employee`),
  INDEX `fk_user_employee1_idx` (`id_employee` ASC),
  CONSTRAINT `fk_user_employee1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Merced_DB`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `Merced_DB`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merced_DB`.`role` (
  `id_role` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `permission` VARCHAR(45) NOT NULL,
  `role_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `id_role_UNIQUE` (`id_role` ASC));

-- -----------------------------------------------------
-- Table `Merced_DB`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Merced_DB`.`user_role` (
  `user_password` VARCHAR(45) NOT NULL,
  `id_employee` INT UNSIGNED NOT NULL,
  `id_role` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_password`, `id_employee`, `id_role`),
  INDEX `fk_user_has_role_role1_idx` (`id_role` ASC),
  INDEX `fk_user_has_role_user1_idx` (`user_password` ASC, `id_employee` ASC),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_password` , `id_employee`)
    REFERENCES `Merced_DB`.`user` (`password` , `id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`id_role`)
    REFERENCES `Merced_DB`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `Merced_DB`.`admon_file`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Merced_DB`.`admon_file` (
  `id_admon` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_organization` INT UNSIGNED NOT NULL,
  `constitutive_act` VARCHAR(10) NOT NULL,
  `fiscal_constance` VARCHAR(10) NOT NULL,
  `compliance_opinion` VARCHAR(10) NOT NULL,
  `curp` VARCHAR(10) NOT NULL,
  `rfc` VARCHAR(14) NOT NULL,
  `address_voucher` VARCHAR(10) NOT NULL,
  `account_status` VARCHAR(10) NOT NULL,
  `official_id` VARCHAR(10) NOT NULL,
  `legal_power` VARCHAR(10) NOT NULL,
  `update_date` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_admon`),
  UNIQUE INDEX `id_finantial_ally_UNIQUE` (`id_admon` ASC) ,
  INDEX `fk_admon_file_organization1_idx` (`id_organization` ASC) ,
  CONSTRAINT `fk_admon_file_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);    

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
