-- MySQL Script generated by MySQL Workbench
-- sáb 26 jun 2021 10:04:46 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Merced_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Merced_DB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Merced_DB` ;
USE `Merced_DB` ;

-- -----------------------------------------------------
-- Table `Merced_DB`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`organization` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`organization` (
  `id_organization` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `org_name` VARCHAR(50) NOT NULL,
  `intervention_area` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `municipality` VARCHAR(45) NOT NULL,
  `blacklist` TEXT(2) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `postal_code` TEXT(5) NOT NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`id_organization`),
  UNIQUE INDEX `id_organizacion_UNIQUE` (`id_organization` ASC) );


-- -----------------------------------------------------
-- Table `Merced_DB`.`program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`program` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`program` (
  `id_program` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `program_code` VARCHAR(45) NOT NULL,
  `program_name` VARCHAR(45) NOT NULL,
  `id_organization` INT UNSIGNED NOT NULL,
  `strategy_line` VARCHAR(45) NOT NULL,
  `strategy_line2` VARCHAR(45) NOT NULL,
  `in_account` VARCHAR(30) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  UNIQUE INDEX `id_programa_UNIQUE` (`id_program` ASC) ,
  INDEX `fk_program_organization1_idx` (`id_organization` ASC) ,
  PRIMARY KEY (`id_program`),
  CONSTRAINT `fk_program_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Merced_DB`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`contact` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`contact` (
  `id_contact` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(10) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `phone _number` INT(10) NOT NULL,
  `phone_number2` INT(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_organization` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_contact`),
  INDEX `fk_contact_organization1_idx` (`id_organization` ASC) ,
  CONSTRAINT `fk_contact_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Merced_DB`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`employee` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`employee` (
  `id_employee` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employee`),
  UNIQUE INDEX `id_leader_UNIQUE` (`id_employee` ASC) );


-- -----------------------------------------------------
-- Table `Merced_DB`.`consultor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`consultor` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`consultor` (
  `id_consultor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `phone2` VARCHAR(10) NULL,
  `email` VARCHAR(45) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `postal_code` TEXT(5) NOT NULL,
  PRIMARY KEY (`id_consultor`),
  UNIQUE INDEX `id_consultor_UNIQUE` (`id_consultor` ASC) );


-- -----------------------------------------------------
-- Table `Merced_DB`.`fort_participation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`fort_participation` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`fort_participation` (
  `id_part` INT UNSIGNED NOT NULL,
  `id_organization` INT UNSIGNED NOT NULL,
  `id_program` INT UNSIGNED NOT NULL,
  `id_consultor` INT UNSIGNED NOT NULL,
  `consultor2` VARCHAR(45) NOT NULL,
  `consultor3` VARCHAR(45) NOT NULL,
  `consultor4` VARCHAR(45) NOT NULL,
  `consultor5` VARCHAR(45) NOT NULL,
  `consultor6` VARCHAR(45) NOT NULL,
  `consultor7` VARCHAR(45) NOT NULL,
  `consultor8` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  `ally_name` VARCHAR(45) NOT NULL,
  `project_name` VARCHAR(50) NOT NULL,
  `project_objective` VARCHAR(100) NOT NULL,
  `male_beneficiaries` INT NOT NULL,
  `female_beneficiaries` INT NOT NULL,
  `population_type` VARCHAR(50) NOT NULL,
  `start_date` VARCHAR(10) NOT NULL,
  `end_date` VARCHAR(10) NOT NULL,
  `achievments` VARCHAR(100) NOT NULL,
  `application_state` VARCHAR(45) NOT NULL,
  `municipality` VARCHAR(50) NOT NULL,
  `application_community` VARCHAR(50) NOT NULL,
  `resources_invested` FLOAT NOT NULL,
  `comments` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_part`, `id_organization`),
  INDEX `fk_program_has_organization_organization1_idx` (`id_organization` ASC) ,
  INDEX `fk_program_organization_program1_idx` (`id_program` ASC) ,
  INDEX `fk_program_organization_consultor1_idx` (`id_consultor` ASC) ,
  CONSTRAINT `fk_program_has_organization_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_organization_program1`
    FOREIGN KEY (`id_program`)
    REFERENCES `Merced_DB`.`program` (`id_program`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_organization_consultor1`
    FOREIGN KEY (`id_consultor`)
    REFERENCES `Merced_DB`.`consultor` (`id_consultor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Merced_DB`.`admon_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`admon_file` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`admon_file` (
  `id_admon` INT UNSIGNED NOT NULL,
  `id_organization` INT UNSIGNED NOT NULL,
  `constitutive_act` VARCHAR(10) NOT NULL,
  `fiscal_constance` VARCHAR(10) NOT NULL,
  `compliance_opinion` VARCHAR(10) NOT NULL,
  `curp` VARCHAR(10) NOT NULL,
  `rfc` VARCHAR(14) NOT NULL,
  `address_voucher` VARCHAR(10) NOT NULL,
  `account_status` VARCHAR(10) NOT NULL,
  `official_id` VARCHAR(10) NOT NULL,
  `legal_power` VARCHAR(10) NOT NULL,
  `update_date` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_admon`),
  UNIQUE INDEX `id_finantial_ally_UNIQUE` (`id_admon` ASC) ,
  INDEX `fk_admon_file_organization1_idx` (`id_organization` ASC) ,
  CONSTRAINT `fk_admon_file_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Merced_DB`.`invsoc_participation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Merced_DB`.`invsoc_participation` ;

CREATE TABLE IF NOT EXISTS `Merced_DB`.`invsoc_participation` (
  `id_partIS` INT UNSIGNED NOT NULL,
  `id_organization` INT UNSIGNED NOT NULL,
  `id_program` INT UNSIGNED NOT NULL,
  `id_consultor` INT UNSIGNED NOT NULL,
  `consultor2` VARCHAR(45) NULL,
  `consultor3` VARCHAR(45) NULL,
  `theme` VARCHAR(45) NOT NULL,
  `announcement_year` VARCHAR(4) NOT NULL,
  `project_name` VARCHAR(50) NOT NULL,
  `project_objective` VARCHAR(100) NOT NULL,
  `population_type` VARCHAR(50) NOT NULL,
  `male_beneficiaries` INT UNSIGNED NOT NULL,
  `female_beneficiaries` INT UNSIGNED NOT NULL,
  `project_type` VARCHAR(12) NOT NULL,
  `start_date` VARCHAR(10) NULL,
  `end_date` VARCHAR(10) NULL,
  `resources` VARCHAR(20) NULL,
  `ally_name` VARCHAR(45) NULL,
  `achievments` VARCHAR(100) NULL,
  `application_state` VARCHAR(45) NULL,
  `application_community` VARCHAR(45) NULL,
  `resources_invested` FLOAT NULL,
  `formation_theme` VARCHAR(45) NULL,
  `num_sessions` INT NULL,
  `fort_theme` VARCHAR(45) NULL,
  `num_sessions_fort` INT NULL,
  `comments` VARCHAR(300) NULL,
  INDEX `fk_table1_program1_idx` (`id_program` ASC) ,
  INDEX `fk_table1_organization1_idx` (`id_organization` ASC) ,
  PRIMARY KEY (`id_partIS`, `id_consultor`, `id_program`, `id_organization`),
  UNIQUE INDEX `id_partIS_UNIQUE` (`id_partIS` ASC) ,
  INDEX `fk_invsoc_participation_consultor1_idx` (`id_consultor` ASC) ,
  CONSTRAINT `fk_table1_program1`
    FOREIGN KEY (`id_program`)
    REFERENCES `Merced_DB`.`program` (`id_program`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_organization1`
    FOREIGN KEY (`id_organization`)
    REFERENCES `Merced_DB`.`organization` (`id_organization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invsoc_participation_consultor1`
    FOREIGN KEY (`id_consultor`)
    REFERENCES `Merced_DB`.`consultor` (`id_consultor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
